### PR TITLE
fix: publish workflow

### PR DESCRIPTION
**Pull request by mateushnsoares**

### CODE REVIEW

**Review by Mikael-R — CHANGES_REQUESTED** [review]
Its ``yarn build`` and not ``yarn compile-build``

**Comment by mateushnsoares** [comment]
> Its `yarn build` and not `yarn compile-build`

interesting, you commented it after that I had changed ;-; kkk

**Comment by Mikael-R** [comment]
Oh really? For me it remains the same ...

**Comment by mateushnsoares** [comment]
I think that now is correct kkk

**Review by Mikael-R — APPROVED** [review]

**Pull request merged**
